apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ollama-pod
  name: ollama-pod
  namespace: ollama
spec:
  volumes: 
    - name: ollama-storage
      persistentVolumeClaim:
        claimName: ollama-claim
  containers:
  - image: ollama/ollama:latest
    name: ollama-pod
    volumeMounts:
    - mountPath: /root/.ollama
      name: ollama-storage 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-claim
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
  labels:
    run: ollama-pod
spec:
  type: ClusterIP
  selector:
    run: ollama-pod
  ports:
    - name: ollama
      protocol: TCP
      port: 8000
      targetPort: 11434