{
 "title": "00 Dashboard for Helloworld",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Helloworld HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "flask_http_request_total", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Helloworld Http Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_total{status=\"404\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Pod Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{pod=\"database-postgresql-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}