apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: maig123/homepage:1
        ports:
        - containerPort: 80
        # env: 
        # - name: POSTGRES_HOST
        #   value: "database-postgresql"
        # - name: DATABASE_NAME
        #   value: "postgres"
        # - name: DB_USER
        #   value: "postgres"
        # - name: DB_PASSWORD
        #   valueFrom: 
        #     secretKeyRef:
        #       name: database-postgresql
        #       key: postgres-password      

  
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld
spec:
  type: ClusterIP
  selector:
    app: helloworld
  ports:
    - name: flask
      protocol: TCP
      port: 8000
      targetPort: 80
    

# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: helloworld-flask-monitor
#   labels:
#     app: helloworld
#     release: monitoring
# spec:
#   selector:
#     matchLabels:
#       app: helloworld
#   namespaceSelector:
#     matchNames:
#     - helloworld
#   endpoints:
#   - port: flask
#     path: /metrics
#     interval: 15s


--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
spec:
  hosts:
  - "rabbitone.io"
  gateways:
  - istio-ingress/helloworld-gateway
  http:
  - match:
    - uri:
        exact: "/"
    - uri: 
        exact: "/projects"
    - uri: 
        prefix: "/assets"
    route:
    - destination:
        port:
          number: 8000
        host: helloworld-service

